# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Server import DHCP_server
import threading
from queue import Queue
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 714)
        MainWindow.setMinimumSize(QtCore.QSize(590, 714))
        MainWindow.setMaximumSize(QtCore.QSize(590, 714))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(-20, -40, 921, 901))
        self.MainFrame.setMinimumSize(QtCore.QSize(921, 901))
        self.MainFrame.setMaximumSize(QtCore.QSize(921, 901))
        self.MainFrame.setStyleSheet("background-color: rgb(234, 250, 255);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.OutputReadOnly = QtWidgets.QTextEdit(self.MainFrame)
        self.OutputReadOnly.setGeometry(QtCore.QRect(50, 460, 531, 251))
        self.OutputReadOnly.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.OutputReadOnly.setReadOnly(True)
        self.OutputReadOnly.setObjectName("OutputReadOnly")
        self.TextStartAddr = QtWidgets.QLineEdit(self.MainFrame)
        self.TextStartAddr.setGeometry(QtCore.QRect(50, 110, 251, 41))
        self.TextStartAddr.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.TextStartAddr.setObjectName("TextStartAddr")
        self.TextEndAddr = QtWidgets.QLineEdit(self.MainFrame)
        self.TextEndAddr.setGeometry(QtCore.QRect(330, 110, 251, 41))
        self.TextEndAddr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TextEndAddr.setObjectName("TextEndAddr")
        self.TextHostN = QtWidgets.QLineEdit(self.MainFrame)
        self.TextHostN.setGeometry(QtCore.QRect(50, 220, 251, 41))
        self.TextHostN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TextHostN.setObjectName("TextHostN")
        self.TextLeaseT = QtWidgets.QLineEdit(self.MainFrame)
        self.TextLeaseT.setGeometry(QtCore.QRect(330, 220, 251, 41))
        self.TextLeaseT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TextLeaseT.setObjectName("TextLeaseT")
        self.TextDomainS = QtWidgets.QLineEdit(self.MainFrame)
        self.TextDomainS.setGeometry(QtCore.QRect(50, 330, 251, 41))
        self.TextDomainS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TextDomainS.setObjectName("TextDomainS")
        self.TextNetmask = QtWidgets.QLineEdit(self.MainFrame)
        self.TextNetmask.setGeometry(QtCore.QRect(330, 330, 251, 41))
        self.TextNetmask.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TextNetmask.setObjectName("TextNetmask")
        self.ButtonSave = QtWidgets.QPushButton(self.MainFrame)
        self.ButtonSave.setGeometry(QtCore.QRect(480, 400, 101, 31))
        self.ButtonSave.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ButtonSave.setObjectName("ButtonSave")
        self.LabelStartA = QtWidgets.QLabel(self.MainFrame)
        self.LabelStartA.setGeometry(QtCore.QRect(130, 70, 151, 21))
        self.LabelStartA.setObjectName("LabelStartA")
        self.LabelEndA = QtWidgets.QLabel(self.MainFrame)
        self.LabelEndA.setGeometry(QtCore.QRect(410, 70, 151, 21))
        self.LabelEndA.setMinimumSize(QtCore.QSize(151, 0))
        self.LabelEndA.setObjectName("LabelEndA")
        self.LabelHostN = QtWidgets.QLabel(self.MainFrame)
        self.LabelHostN.setGeometry(QtCore.QRect(140, 180, 151, 21))
        self.LabelHostN.setObjectName("LabelHostN")
        self.LabelLeaseT = QtWidgets.QLabel(self.MainFrame)
        self.LabelLeaseT.setGeometry(QtCore.QRect(410, 180, 151, 21))
        self.LabelLeaseT.setObjectName("LabelLeaseT")
        self.LabelDomainS = QtWidgets.QLabel(self.MainFrame)
        self.LabelDomainS.setGeometry(QtCore.QRect(130, 290, 151, 21))
        self.LabelDomainS.setObjectName("LabelDomainS")
        self.LabelNetmask = QtWidgets.QLabel(self.MainFrame)
        self.LabelNetmask.setGeometry(QtCore.QRect(420, 290, 151, 21))
        self.LabelNetmask.setObjectName("LabelNetmask")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server DHCP"))
        self.ButtonSave.setText(_translate("MainWindow", "Save Settings"))
        self.LabelStartA.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Start Address</span></p></body></html>"))
        self.LabelEndA.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">End Address</span></p><p><br/></p></body></html>"))
        self.LabelHostN.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Host Name</span></p><p><br/></p></body></html>"))
        self.LabelLeaseT.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Lease time</span></p><p><br/></p></body></html>"))
        self.LabelDomainS.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Domain Server</span></p><p><br/></p></body></html>"))
        self.LabelNetmask.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Netmask</span></p><p><br/></p></body></html>"))

    def adaugaText(self, x):
        y = self.OutputReadOnly.toPlainText()
        z = y+x
        self.OutputReadOnly.setText(z)

    def completariStatice(self):
        self.TextStartAddr.setText("192.168.1.2")
        self.TextEndAddr.setText("192.168.1.50")
        self.TextHostN.setText("Server blana")
        self.TextLeaseT.setText("86400 secunde")
        self.TextDomainS.setText("192.168.1.1")
        self.TextNetmask.setText("255.255.255.0")


def interfata(out_q):
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.completariStatice()

    def log():
        data = out_q.get()
        if(data):
            ui.adaugaText(data)
        else:
            pass
    timer = QtCore.QTimer()
    timer.timeout.connect(log)
    timer.start(1000)
    sys.exit(app.exec_())


if __name__ == "__main__":
    q = Queue()
    dhcp_server = DHCP_server()
    x = threading.Thread(target=dhcp_server.server, args=(q,)).start()
    y = threading.Thread(target=interfata, args=(q,)).start()
